# Summarizing statistics

In [1]:
import numpy as np
import pandas as pd

## Loading data

In [2]:
df_variables = pd.read_csv("data/df_base_without_missing_points.csv", index_col=0)

In [26]:
df_deaths = pd.read_csv('data/df_mortality.csv', index_col=0)

In [3]:
df_labeled_cluster = pd.read_csv('data/df_labeled_cluster.csv', index_col=0)

## Analysis

### Analysis for national data

In [4]:
df_variables_analysis = df_variables[df_variables.columns[7:]]

In [6]:
statistics = []
for column in df_variables_analysis.columns:
    mean = df_variables_analysis[column].mean()
    std_dev = df_variables_analysis[column].std()
    median = df_variables_analysis[column].median()
    q1 = df_variables_analysis[column].quantile(0.25)
    q3 = df_variables_analysis[column].quantile(0.75)
    statistics.append({
        'Variable': column,
        'Mean (SD)': f"{mean:.2f} ({std_dev:.2f})",
        'Median (Q1, Q3)': f"{median:.2f} ({q1:.2f}, {q3:.2f})"
    })

# Create a new DataFrame with the calculated statistics
df_statistics = pd.DataFrame(statistics)

In [7]:
df_statistics = df_statistics.set_index('Variable')

In [8]:
len(df_statistics)

31

In [9]:
df_statistics.index

Index(['percentage_population_age_range_0_19',
       'percentage_population_age_range_20_39',
       'percentage_population_age_range_40_59',
       'percentage_population_age_range_60_more',
       'percentage_urban_population', 'average_residents_per_households',
       'percentage_population_in_households_more_2_residents_per_bedroom',
       'percentage_male_population', 'percentage_indigenous_population',
       'percentage_black_and_brown_population', 'life_expectancy_at_birth',
       'density_median_effectively_domiciled_area', 'per_capita_income',
       'gini', 'per_capita_cash_transfer_program',
       'percentage_estimated_households_in_informal_settlements',
       'percentage_population_in_informal_settlements',
       'demographic_density_in_informal_settlements',
       'percentage_population_in_households_without_bathroom',
       'percentage_hospitalizations_diseases_inadequate_sanitation',
       'activity_rate', 'percentage_self_employed_workers',
       'unemployment_rate', 'percentage_informal_workers',
       'percentage_poor_population_spending_more_1_hour_to_work',
       'percentage_workers_agriculture', 'percentage_workers_commerce',
       'percentage_workers_services', 'percentage_workers_industry',
       'illiteracy_rate', 'expected_years_of_schooling_at_age_18'],
      dtype='object', name='Variable')

In [10]:
variable_labels = ['% population 0-19 years',
                   '% population 20-39 years',
                   '% population 40-59 years',
                   '% population 60+ years',
                   '% urban population',
                   'Average household size',
                   '% crowded households',
                   '% male population',
                   '% indigenous population',
                   '% black and brown population',
                   'Life expectancy (years)',
                   'Median density of effectively domiciled areas (inhabitants/km²)',
                   'Per capita income (BRL)',
                   'Gini coefficient',
                   'Social transfer per capita (BRL)',
                   '% informal settlement households',
                   '% population in informal settlements',
                   'Population density in informal settlement (inhabitants/ha)',
                   '% households without bathroom',
                   '% sanitation-related hospitalizations',
                   'Activity rate',
                   '% self-employed workers', 
                   'Unemployment rate',
                   '% informal workers',
                   '% poor population spending 1+ hour to work',
                   '% agriculture workers',
                   '% commerce workers', 
                   '% service workers', 
                   '% industry workers',
                   'Illiteracy rate',
                   'Expected years of schooling at age 18']

In [11]:
df_statistics.index = variable_labels

In [12]:
variable_labels

['% population 0-19 years',
 '% population 20-39 years',
 '% population 40-59 years',
 '% population 60+ years',
 '% urban population',
 'Average household size',
 '% crowded households',
 '% male population',
 '% indigenous population',
 '% black and brown population',
 'Life expectancy (years)',
 'Median density of effectively domiciled areas (inhabitants/km²)',
 'Per capita income (BRL)',
 'Gini coefficient',
 'Social transfer per capita (BRL)',
 '% informal settlement households',
 '% population in informal settlements',
 'Population density in informal settlement (inhabitants/ha)',
 '% households without bathroom',
 '% sanitation-related hospitalizations',
 'Activity rate',
 '% self-employed workers',
 'Unemployment rate',
 '% informal workers',
 '% poor population spending 1+ hour to work',
 '% agriculture workers',
 '% commerce workers',
 '% service workers',
 '% industry workers',
 'Illiteracy rate',
 'Expected years of schooling at age 18']

In [13]:
df_statistics_sorted = df_statistics.loc[np.concatenate((variable_labels[:4], variable_labels[11:12], variable_labels[4:11], variable_labels[12:]))]

In [14]:
df_statistics_sorted

,Mean (SD),"Median (Q1, Q3)"
% population 0-19 years,27.55 (4.85),"26.88 (24.27, 30.12)"
% population 20-39 years,28.76 (2.96),"28.87 (26.96, 30.57)"
% population 40-59 years,26.28 (2.66),"26.72 (24.88, 28.07)"
% population 60+ years,17.43 (4.59),"17.26 (14.33, 20.27)"
Median density of effectively domiciled areas (inhabitants/km²),2880.61 (2043.02),"2447.15 (1585.06, 3610.04)"
% urban population,63.81 (22.04),"64.64 (47.07, 82.16)"
Average household size,2.84 (0.32),"2.78 (2.65, 2.95)"
% crowded households,25.13 (12.99),"23.07 (15.41, 32.58)"
% male population,50.00 (1.58),"49.89 (49.07, 50.77)"
% indigenous population,1.20 (6.14),"0.07 (0.03, 0.19)"
% black and brown population,56.01 (22.66),"60.79 (37.46, 75.30)"
Life expectancy (years),73.09 (2.68),"73.47 (71.15, 75.16)"
Per capita income (BRL),493.34 (242.96),"467.38 (281.03, 650.37)"
Gini coefficient,0.49 (0.07),"0.49 (0.45, 0.54)"
Social transfer per capita (BRL),137.84 (110.38),"99.48 (47.28, 214.78)"
% informal settlement households,1.05 (4.51),"0.00 (0.00, 0.00)"
% population in informal settlements,0.52 (3.28),"0.00 (0.00, 0.00)"
Population density in informal settlement (inhabitants/ha),4.65 (26.60),"0.00 (0.00, 0.00)"
% households without bathroom,3.87 (7.97),"0.43 (0.06, 3.80)"
% sanitation-related hospitalizations,3.16 (4.65),"1.47 (0.59, 3.71)"
Activity rate,55.37 (9.24),"55.63 (49.24, 61.22)"
% self-employed workers,24.69 (9.85),"22.66 (18.08, 28.69)"
Unemployment rate,6.74 (3.83),"6.27 (4.16, 8.62)"
% informal workers,56.51 (19.27),"57.17 (40.26, 73.68)"
% poor population spending 1+ hour to work,1.39 (1.56),"0.90 (0.33, 1.91)"
% agriculture workers,35.57 (18.25),"36.47 (21.84, 49.30)"
% commerce workers,10.57 (4.41),"10.04 (7.25, 13.45)"
% service workers,32.46 (8.89),"31.89 (26.13, 38.00)"
% industry workers,9.61 (8.92),"6.53 (3.32, 13.29)"
Illiteracy rate,11.81 (7.56),"9.38 (5.57, 17.97)"
Expected years of schooling at age 18,9.46 (1.10),"9.47 (8.75, 10.21)"

In [15]:
df_statistics_sorted.to_csv('data/df_sociodemographic_statistics.csv', index=True)

### Analysis by cluster

In [16]:
df_variables['cluster_label'] = df_labeled_cluster['cluster_label']

In [17]:
df_variables_analysis = df_variables[df_variables.columns[7:]]

In [18]:
labels_sorted = ['Urbanized','Urbanized with informal settlements','Semi-urbanized','Rural with high human development','Rural with low human development']

In [19]:
statistics = []
for column in df_variables_analysis.columns[:-1]:
    row = {'Variable': column}
    for cluster in labels_sorted:        
        df_variables_analysis_cluster = df_variables_analysis[df_variables_analysis['cluster_label'] == cluster]
        median = df_variables_analysis_cluster[column].median()
        q1 = df_variables_analysis_cluster[column].quantile(0.25)
        q3 = df_variables_analysis_cluster[column].quantile(0.75)
        row[cluster] = f"{median:.2f} ({q1:.2f}, {q3:.2f})"
    statistics.append(row)

# Create a new DataFrame with the calculated statistics
df_statistics = pd.DataFrame(statistics)

In [20]:
df_statistics = df_statistics.set_index('Variable')

In [21]:
df_statistics

,Urbanized,Urbanized with informal settlements,Semi-urbanized,Rural with high human development,Rural with low human development
Variable,,,,,
percentage_population_age_range_0_19,"25.06 (23.44, 26.83)","27.79 (25.70, 30.45)","29.60 (27.60, 31.81)","23.05 (21.10, 24.95)","38.21 (35.66, 41.98)"
percentage_population_age_range_20_39,"28.63 (27.03, 30.30)","31.59 (30.13, 33.23)","29.29 (27.94, 30.68)","25.59 (23.88, 27.16)","30.77 (29.41, 31.96)"
percentage_population_age_range_40_59,"27.57 (26.69, 28.48)","26.81 (24.99, 27.77)","25.16 (23.92, 26.39)","28.38 (27.40, 29.44)","20.12 (18.37, 21.86)"
percentage_population_age_range_60_more,"18.56 (16.24, 20.80)","13.59 (11.14, 15.99)","15.74 (13.77, 17.88)","22.53 (20.23, 25.41)","10.26 (8.20, 12.53)"
percentage_urban_population,"82.69 (74.07, 90.72)","95.17 (88.42, 99.28)","54.48 (41.14, 65.88)","47.36 (34.06, 58.47)","43.27 (31.43, 53.02)"
average_residents_per_households,"2.69 (2.61, 2.78)","2.83 (2.71, 2.96)","2.92 (2.80, 3.05)","2.62 (2.54, 2.71)","3.55 (3.34, 4.02)"
percentage_population_in_households_more_2_residents_per_bedroom,"17.50 (13.50, 22.00)","31.27 (25.54, 38.49)","30.88 (25.62, 36.66)","11.63 (8.24, 15.72)","53.40 (45.70, 65.30)"
percentage_male_population,"49.53 (48.89, 50.20)","48.16 (47.53, 48.86)","50.01 (49.21, 50.86)","50.65 (49.99, 51.32)","51.18 (50.34, 51.91)"
percentage_indigenous_population,"0.07 (0.03, 0.13)","0.15 (0.09, 0.29)","0.09 (0.03, 0.31)","0.03 (0.00, 0.10)","0.16 (0.05, 8.18)"
percentage_black_and_brown_population,"43.96 (32.51, 56.62)","68.82 (55.23, 74.98)","74.63 (66.63, 80.69)","25.56 (15.04, 41.89)","81.48 (74.50, 85.97)"
life_expectancy_at_birth,"75.06 (74.01, 76.01)","74.24 (72.97, 75.65)","70.99 (69.69, 72.32)","74.70 (73.62, 75.81)","70.07 (68.44, 71.38)"
density_median_effectively_domiciled_area,"2737.49 (1979.37, 3600.55)","6650.86 (4888.58, 9000.86)","2477.85 (1713.30, 3641.04)","1174.42 (732.94, 1706.26)","2520.89 (1782.06, 3771.44)"
per_capita_income,"645.37 (550.30, 768.66)","600.48 (449.73, 799.41)","278.00 (238.35, 334.92)","586.84 (480.01, 729.03)","195.22 (169.40, 228.03)"
gini,"0.46 (0.42, 0.50)","0.52 (0.47, 0.56)","0.52 (0.49, 0.55)","0.46 (0.42, 0.49)","0.59 (0.55, 0.62)"
per_capita_cash_transfer_program,"49.88 (30.71, 75.68)","78.57 (44.63, 121.40)","219.46 (163.72, 280.04)","52.05 (26.61, 82.12)","307.95 (249.75, 385.25)"
percentage_estimated_households_in_informal_settlements,"0.00 (0.00, 0.00)","7.49 (2.81, 15.99)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
percentage_population_in_informal_settlements,"0.00 (0.00, 0.00)","3.61 (0.00, 10.98)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
demographic_density_in_informal_settlements,"0.00 (0.00, 0.00)","37.04 (0.00, 93.56)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
percentage_population_in_households_without_bathroom,"0.06 (0.02, 0.17)","0.25 (0.09, 0.85)","3.68 (1.59, 7.52)","0.12 (0.03, 0.38)","25.76 (17.55, 36.41)"
percentage_hospitalizations_diseases_inadequate_sanitation,"0.91 (0.40, 2.00)","0.79 (0.43, 1.48)","2.42 (1.03, 5.50)","1.25 (0.40, 2.73)","7.29 (3.10, 14.68)"
activity_rate,"59.32 (55.74, 62.65)","57.29 (53.53, 60.74)","49.45 (44.84, 53.97)","63.97 (58.04, 71.19)","47.10 (41.09, 51.36)"
percentage_self_employed_workers,"20.11 (16.99, 24.03)","19.66 (17.12, 22.39)","22.67 (18.12, 27.84)","35.04 (27.34, 44.71)","28.04 (21.88, 36.34)"
unemployment_rate,"5.91 (4.35, 7.51)","10.07 (8.05, 12.16)","7.52 (5.52, 10.08)","2.48 (1.36, 3.94)","6.88 (4.81, 9.59)"
percentage_informal_workers,"38.51 (30.19, 47.72)","37.83 (28.98, 46.61)","73.62 (65.32, 79.66)","56.71 (46.87, 65.49)","82.08 (76.54, 86.80)"
percentage_poor_population_spending_more_1_hour_to_work,"0.43 (0.19, 0.90)","1.33 (0.67, 2.89)","1.61 (0.94, 2.52)","0.27 (0.06, 0.70)","3.78 (2.38, 5.50)"
percentage_workers_agriculture,"21.33 (12.65, 30.17)","3.85 (1.27, 10.82)","43.94 (34.84, 52.24)","50.44 (42.89, 58.87)","54.11 (44.70, 61.52)"
percentage_workers_commerce,"12.34 (9.77, 14.97)","16.45 (14.53, 19.27)","9.20 (6.84, 11.75)","6.96 (5.40, 8.77)","7.37 (5.10, 9.57)"
percentage_workers_services,"36.00 (31.29, 41.36)","46.71 (41.64, 51.34)","30.38 (25.92, 35.08)","24.51 (20.18, 29.37)","25.85 (21.91, 30.30)"
percentage_workers_industry,"13.86 (7.72, 21.34)","10.09 (6.58, 16.06)","3.63 (2.21, 5.96)","6.48 (3.58, 10.54)","2.70 (1.64, 4.31)"
illiteracy_rate,"5.78 (4.18, 7.78)","4.94 (3.35, 9.03)","18.82 (14.28, 22.60)","6.72 (4.38, 9.02)","20.14 (14.36, 24.78)"
expected_years_of_schooling_at_age_18,"9.99 (9.37, 10.60)","9.49 (9.02, 9.98)","8.94 (8.41, 9.48)","10.21 (9.50, 10.88)","8.11 (7.37, 8.82)"

In [22]:
df_statistics.index = variable_labels

In [23]:
df_statistics_sorted = df_statistics.loc[np.concatenate((variable_labels[:4], variable_labels[11:12], variable_labels[4:11], variable_labels[12:]))]

In [24]:
df_statistics_sorted

,Urbanized,Urbanized with informal settlements,Semi-urbanized,Rural with high human development,Rural with low human development
% population 0-19 years,"25.06 (23.44, 26.83)","27.79 (25.70, 30.45)","29.60 (27.60, 31.81)","23.05 (21.10, 24.95)","38.21 (35.66, 41.98)"
% population 20-39 years,"28.63 (27.03, 30.30)","31.59 (30.13, 33.23)","29.29 (27.94, 30.68)","25.59 (23.88, 27.16)","30.77 (29.41, 31.96)"
% population 40-59 years,"27.57 (26.69, 28.48)","26.81 (24.99, 27.77)","25.16 (23.92, 26.39)","28.38 (27.40, 29.44)","20.12 (18.37, 21.86)"
% population 60+ years,"18.56 (16.24, 20.80)","13.59 (11.14, 15.99)","15.74 (13.77, 17.88)","22.53 (20.23, 25.41)","10.26 (8.20, 12.53)"
Median density of effectively domiciled areas (inhabitants/km²),"2737.49 (1979.37, 3600.55)","6650.86 (4888.58, 9000.86)","2477.85 (1713.30, 3641.04)","1174.42 (732.94, 1706.26)","2520.89 (1782.06, 3771.44)"
% urban population,"82.69 (74.07, 90.72)","95.17 (88.42, 99.28)","54.48 (41.14, 65.88)","47.36 (34.06, 58.47)","43.27 (31.43, 53.02)"
Average household size,"2.69 (2.61, 2.78)","2.83 (2.71, 2.96)","2.92 (2.80, 3.05)","2.62 (2.54, 2.71)","3.55 (3.34, 4.02)"
% crowded households,"17.50 (13.50, 22.00)","31.27 (25.54, 38.49)","30.88 (25.62, 36.66)","11.63 (8.24, 15.72)","53.40 (45.70, 65.30)"
% male population,"49.53 (48.89, 50.20)","48.16 (47.53, 48.86)","50.01 (49.21, 50.86)","50.65 (49.99, 51.32)","51.18 (50.34, 51.91)"
% indigenous population,"0.07 (0.03, 0.13)","0.15 (0.09, 0.29)","0.09 (0.03, 0.31)","0.03 (0.00, 0.10)","0.16 (0.05, 8.18)"
% black and brown population,"43.96 (32.51, 56.62)","68.82 (55.23, 74.98)","74.63 (66.63, 80.69)","25.56 (15.04, 41.89)","81.48 (74.50, 85.97)"
Life expectancy (years),"75.06 (74.01, 76.01)","74.24 (72.97, 75.65)","70.99 (69.69, 72.32)","74.70 (73.62, 75.81)","70.07 (68.44, 71.38)"
Per capita income (BRL),"645.37 (550.30, 768.66)","600.48 (449.73, 799.41)","278.00 (238.35, 334.92)","586.84 (480.01, 729.03)","195.22 (169.40, 228.03)"
Gini coefficient,"0.46 (0.42, 0.50)","0.52 (0.47, 0.56)","0.52 (0.49, 0.55)","0.46 (0.42, 0.49)","0.59 (0.55, 0.62)"
Social transfer per capita (BRL),"49.88 (30.71, 75.68)","78.57 (44.63, 121.40)","219.46 (163.72, 280.04)","52.05 (26.61, 82.12)","307.95 (249.75, 385.25)"
% informal settlement households,"0.00 (0.00, 0.00)","7.49 (2.81, 15.99)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
% population in informal settlements,"0.00 (0.00, 0.00)","3.61 (0.00, 10.98)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
Population density in informal settlement (inhabitants/ha),"0.00 (0.00, 0.00)","37.04 (0.00, 93.56)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)","0.00 (0.00, 0.00)"
% households without bathroom,"0.06 (0.02, 0.17)","0.25 (0.09, 0.85)","3.68 (1.59, 7.52)","0.12 (0.03, 0.38)","25.76 (17.55, 36.41)"
% sanitation-related hospitalizations,"0.91 (0.40, 2.00)","0.79 (0.43, 1.48)","2.42 (1.03, 5.50)","1.25 (0.40, 2.73)","7.29 (3.10, 14.68)"
Activity rate,"59.32 (55.74, 62.65)","57.29 (53.53, 60.74)","49.45 (44.84, 53.97)","63.97 (58.04, 71.19)","47.10 (41.09, 51.36)"
% self-employed workers,"20.11 (16.99, 24.03)","19.66 (17.12, 22.39)","22.67 (18.12, 27.84)","35.04 (27.34, 44.71)","28.04 (21.88, 36.34)"
Unemployment rate,"5.91 (4.35, 7.51)","10.07 (8.05, 12.16)","7.52 (5.52, 10.08)","2.48 (1.36, 3.94)","6.88 (4.81, 9.59)"
% informal workers,"38.51 (30.19, 47.72)","37.83 (28.98, 46.61)","73.62 (65.32, 79.66)","56.71 (46.87, 65.49)","82.08 (76.54, 86.80)"
% poor population spending 1+ hour to work,"0.43 (0.19, 0.90)","1.33 (0.67, 2.89)","1.61 (0.94, 2.52)","0.27 (0.06, 0.70)","3.78 (2.38, 5.50)"
% agriculture workers,"21.33 (12.65, 30.17)","3.85 (1.27, 10.82)","43.94 (34.84, 52.24)","50.44 (42.89, 58.87)","54.11 (44.70, 61.52)"
% commerce workers,"12.34 (9.77, 14.97)","16.45 (14.53, 19.27)","9.20 (6.84, 11.75)","6.96 (5.40, 8.77)","7.37 (5.10, 9.57)"
% service workers,"36.00 (31.29, 41.36)","46.71 (41.64, 51.34)","30.38 (25.92, 35.08)","24.51 (20.18, 29.37)","25.85 (21.91, 30.30)"
% industry workers,"13.86 (7.72, 21.34)","10.09 (6.58, 16.06)","3.63 (2.21, 5.96)","6.48 (3.58, 10.54)","2.70 (1.64, 4.31)"
Illiteracy rate,"5.78 (4.18, 7.78)","4.94 (3.35, 9.03)","18.82 (14.28, 22.60)","6.72 (4.38, 9.02)","20.14 (14.36, 24.78)"
Expected years of schooling at age 18,"9.99 (9.37, 10.60)","9.49 (9.02, 9.98)","8.94 (8.41, 9.48)","10.21 (9.50, 10.88)","8.11 (7.37, 8.82)"

In [25]:
df_statistics_sorted.to_csv('data/df_sociodemographic_cluster_statistics.csv', index=True)

In [35]:
df_statistics_deaths = df_deaths[['expected_deaths_1s_2020', 'expected_deaths_2020', 'expected_deaths_2021', 'expected_deaths_2022', 'expected_deaths_entire']].describe().T[['mean','std','50%','25%','75%']]

In [36]:
df_statistics_deaths

,mean,std,50%,25%,75%
expected_deaths_1s_2020,33373.610252,60057.841004,9017.5,0.00,39711.75
expected_deaths_2020,132683.882914,105810.515536,111182.5,56274.00,186831.00
expected_deaths_2021,342614.742806,188291.231765,316697.5,200719.00,454850.50
expected_deaths_2022,58296.018345,49911.924880,50921.0,24662.00,81084.00
expected_deaths_entire,533594.657014,254935.572058,502554.5,346675.75,691419.75

In [37]:
df_statistics_deaths.to_csv('data/df_statistics_deaths.csv', index=True)

In [38]:
df_deaths

,code_municipality_6,code_municipality_7,population,date,region,deaths,new_deaths,deaths_accumulated_first_semester_2020,delta_first_death_2020-06-30,deaths_accumulated_2020,...,expected_deaths_entire,SMR_1s_2020,expected_deaths_1s_2020,SMR_2020,expected_deaths_2020,SMR_2021,expected_deaths_2021,SMR_2022,expected_deaths_2022,inverse_death_weighted_SMR
0,110001,1100015,21495,2022-12-31,North,93.0,0.0,0.0,0.0,16.0,...,927589.0,0.000000,0.0,81.397176,165302.0,326.452891,662963.0,48.908622,99324.0,84.999061
1,110002,1100023,96833,2022-12-31,North,540.0,0.0,20.0,44.0,122.0,...,1457150.0,24.894038,50555.0,160.620832,326190.0,504.112758,1023756.0,52.788852,107204.0,123.047283
2,110003,1100031,5363,2022-12-31,North,15.0,0.0,1.0,0.0,4.0,...,480554.0,13.141078,26687.0,71.951180,146119.0,152.495985,309690.0,12.184808,24745.0,39.547968
3,110004,1100049,86895,2022-12-31,North,351.0,0.0,6.0,85.0,60.0,...,930313.0,7.787050,15814.0,77.981293,158365.0,343.801163,698194.0,36.317572,73754.0,77.494077
4,110005,1100056,15890,2022-12-31,North,76.0,0.0,2.0,41.0,8.0,...,1042295.0,12.169543,24714.0,57.032977,115823.0,383.454846,778723.0,72.753324,147748.0,102.197185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,522200,5222005,14956,2022-12-31,Midwestern,47.0,0.0,0.0,0.0,7.0,...,651089.0,0.000000,0.0,46.779420,95000.0,217.209158,441110.0,56.617871,114980.0,71.476035
5566,522205,5222054,8768,2022-12-31,Midwestern,34.0,0.0,1.0,20.0,8.0,...,973173.0,15.117139,30700.0,123.098813,249990.0,345.055836,700742.0,11.050776,22442.0,69.829597
5567,522220,5222203,4215,2022-12-31,Midwestern,7.0,0.0,0.0,0.0,2.0,...,653860.0,0.000000,0.0,96.067202,195094.0,116.817075,237233.0,109.086653,221534.0,107.162622
5568,522230,5222302,5815,2022-12-31,Midwestern,11.0,0.0,1.0,2.0,3.0,...,390316.0,21.654932,43977.0,58.049813,117888.0,121.589069,246924.0,12.558551,25504.0,33.621383
5569,530010,5300108,2817068,2022-12-31,Midwestern,9685.0,1.0,564.0,99.0,3098.0,...,811205.0,23.606865,47941.0,130.072886,264153.0,238.490840,484329.0,30.885743,62723.0,73.635251